[phases.setup]
aptPkgs = ["libgomp1"]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python3 -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/gunicorn app:app"